---
Description: CFN Canary CRUD ProtectionGroup
Parameters:
  ProtectionGroupId:
    Type: String
    AllowedPattern: "^[a-zA-Z0-9\\-]{1,36}$"

Resources:
  ProtectionGroupToCreateThenUpdate:
    Type: AWS::Shield::ProtectionGroup
    Properties:
      ProtectionGroupId: !Ref ProtectionGroupId
      ProtectionGroupArn: !Sub arn:aws:shield::${AWS::AccountId}:protection-group/${ProtectionGroupId}
      Aggregation: SUM
      Pattern: ARBITRARY
      Members:
        - !ImportValue CanaryTestCloudFrontARN
      ResourceType: CLOUDFRONT_DISTRIBUTION
